const express=require('express')
const dotenv=require('dotenv')
const DataBase =require('../dbconfig/dbconfig')
const fileuploads=require('express-fileupload')
const cors=require('cors')
const {adminRoute} =require('../routes/adminRoutes')
const userRoute=require('../routes/userRoutes')
dotenv.config()
const app=express()
DataBase()
app.use(express.json())
app.use(cors())
app.use(fileuploads())
app.use(adminRoute)
app.use(userRoute)
app.use("/upload",express.static("./uploads"));
//http://localhost:9000/upload/daya.jpg
app.listen(process.env.PORT||5000,()=>{
    console.log(`Server is Ruuning Successfully on Port ${process.env.PORT}`)
})